# ====== PostgreSQL DB Configuration ======
spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# ====== Hibernate & JPA Config ======
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# ====== Spring AI Ollama Configuration ======
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3

# Optional: Logging
#logging.level.org.hibernate.SQL=DEBUG
